CREATE TABLE "organizations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(255) NOT NULL,
	"slug" varchar(100) NOT NULL,
	"display_name" varchar(255),
	"home_region" varchar(10) NOT NULL,
	"billing_country" char(2) NOT NULL,
	"currency" char(3) NOT NULL,
	"tax_profile" varchar(20) DEFAULT 'NONE' NOT NULL,
	"compliance_profile" varchar(20) DEFAULT 'DEFAULT' NOT NULL,
	"billing_email" varchar(255) NOT NULL,
	"tax_id" varchar(100),
	"billing_address" jsonb,
	"plan_tier" varchar(20) DEFAULT 'INDIVIDUAL' NOT NULL,
	"is_trial" boolean DEFAULT false NOT NULL,
	"trial_ends_at" timestamp with time zone DEFAULT NOW() NOT NULL,
	"feature_overrides" jsonb DEFAULT '{}',
	"status" varchar(20) DEFAULT 'active' NOT NULL,
	"suspended_reason" text,
	"industry" varchar(100),
	"company_size" varchar(20),
	"onboarding_completed" boolean DEFAULT false NOT NULL,
	"onboarding_step" varchar(50),
	"settings" jsonb DEFAULT '{}',
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "organizations_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "user_sessions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"org_id" uuid NOT NULL,
	"session_token" varchar(255) NOT NULL,
	"refresh_token" varchar(255),
	"device_type" varchar(20),
	"device_name" varchar(255),
	"os" varchar(50),
	"browser" varchar(50),
	"ip_address" "inet",
	"user_agent" text,
	"location" jsonb,
	"is_active" boolean DEFAULT true NOT NULL,
	"last_activity_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"revoked_at" timestamp with time zone,
	CONSTRAINT "user_sessions_session_token_unique" UNIQUE("session_token")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"org_id" uuid NOT NULL,
	"email" varchar(255) NOT NULL,
	"full_name" varchar(255),
	"nickname" varchar(100),
	"avatar_url" text,
	"role" varchar(20) DEFAULT 'MEMBER' NOT NULL,
	"permissions" jsonb DEFAULT '[]',
	"locale" varchar(10) DEFAULT 'en-US' NOT NULL,
	"time_zone" varchar(50) DEFAULT 'UTC' NOT NULL,
	"theme" varchar(10) DEFAULT 'system',
	"font_size" varchar(10) DEFAULT 'default',
	"contrast_mode" boolean DEFAULT false,
	"notification_preferences" jsonb DEFAULT '{"product_updates": true, "useful_info": true}',
	"status" varchar(20) DEFAULT 'active' NOT NULL,
	"invited_by" uuid,
	"invitation_token" varchar(255),
	"invitation_expires_at" timestamp with time zone,
	"email_verified" boolean DEFAULT false NOT NULL,
	"magic_link_token" varchar(255),
	"magic_link_expires" timestamp with time zone,
	"last_login_at" timestamp with time zone,
	"last_active_at" timestamp with time zone,
	"login_count" integer DEFAULT 0,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "users_org_id_email_unique" UNIQUE("org_id","email")
);
--> statement-breakpoint
ALTER TABLE "user_sessions" ADD CONSTRAINT "user_sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_sessions" ADD CONSTRAINT "user_sessions_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_invited_by_users_id_fk" FOREIGN KEY ("invited_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;